name: Create Pull Request

on:
  push:
    branches:
      - master

jobs:
   create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
      - uses: actions/checkout@v2
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          title: Automated Pull Request
          body: Automated Pull Request
