name: Create Pull Request

on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: 'peter-evans/create-pull-request@v4'
        with:
          branch: dev
          commit-message: Automated Pull Request
          title: Automated Pull Request
