name: Create Pull Request

on:
  push:
    branches:
      - master

jobs:
   create-pull-request:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
=======
      - name: Create Pull Request
      - uses: actions/checkout@v2
>>>>>>> 91d3b390c8bfe52b0efe24ea2241dd8fd0da5bc9
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          title: Automated Pull Request
          body: Automated Pull Request
